# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.11.0-beta
build.parchment=2025.12.20

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.11&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.11&l=neoforge
dep.yacl=3.8.2+1.21.11-neoforge
# figurestonelib, check https://modrinth.com/mod/figurestonelib/versions?g=1.21.11&l=neoforge
dep.figurestonelib=1.0.0+1.21.11+neoforge
