# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.11+build.6
build.fabric_api=0.141.6+1.21.11

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.11&l=fabric
dep.modmenu=17.0.0
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.11&l=fabric
dep.yacl=3.8.2+1.21.11-fabric
# figurestonelib, check https://modrinth.com/mod/figurestonelib/versions?g=1.21.11&l=fabric
dep.figurestonelib=1.0.0+1.21.11+fabric
